# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eeb84971e87d157a9b52f6f8fbd897ed7f9645e46916f92c5f2450a787d1f2f8552347ec45a5531ab7864bb1cf877817e574e7945d2eef8fe43d3bd1cc22ae42

test:
  secret_key_base: 9050182c038128b78b22ce5743f4715512d1e9ea2989106f1ac82a474f53df34a6d3280926758320698b4fcc28beeac71780b8d2f40efa0a78ed6b4e73f3814c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
